public-host: ""
public-port: 0
host: 0.0.0.0
port: 4000
use-cert: false
trusted-x-forwarded-for: false
only-gc-when-start: false
sync-interval: 10
download-max-conn: 16
max-reconnect-count: 10
log-slots: 7
no-access-log: false
access-log-slots: 16
clusters:
  main:
    id: ${CLUSTER_ID}
    secret: ${CLUSTER_SECRET}
    byoc: false
    public-hosts:
      - ""
    server: ""
    skip-signature-check: false
    storages: []
storages:
  - type: local
    id: local-storage-0
    weight: 100
    data:
      cache-path: _cache
      compressor: ""
certificates:
  - cert: /path/to/cert.pem
    key: /path/to/key.pem
tunneler:
  enable: false
  tunnel-program: ./path/to/tunnel/program
  output-regex: \bNATedAddr\s+(?<host>[0-9.]+|\[[0-9a-f:]+\]):(?<port>\d+)$
cache:
  type: inmem
serve-limit:
  enable: false
  max-conn: 16384
  upload-rate: 10240
api-rate-limit:
  anonymous:
    per-minute: 10
    per-hour: 120
  logged:
    per-minute: 120
    per-hour: 6000
notification:
  enable-email: false
  email-smtp: smtp.example.com:25
  email-smtp-encryption: tls
  email-sender: noreply@example.com
  email-sender-password: example-password
  enable-webhook: true
dashboard:
  enable: true
  username: ""
  password: ""
  pwa-name: GoOpenBmclApi Dashboard
  pwa-short_name: GOBA Dash
  pwa-description: Go-Openbmclapi Internal Dashboard
  notification-subject: mailto:user@example.com
github-api:
  update-check-interval: 1h0m0s
  authorization: ""
database:
  driver: sqlite
  data-source-name: files.db
hijack:
  enable: false
  enable-local-cache: false
  local-cache-path: hijack_cache
  require-auth: false
  auth-users:
    - username: example-username
      password: example-password
webdav-users:
  example-user:
    endpoint: https://webdav.example.com/path/to/endpoint/
    username: example-username
    password: example-password
advanced:
  debug-log: false
  socket-io-log: false
  no-heavy-check: false
  no-gc: false
  heavy-check-interval: 120
  keepalive-timeout: 10
  no-fast-enable: false
  wait-before-enable: 0
  do-not-open-faq-on-windows: false
